services:
  api:
    image: ghcr.io/varun-sai-500/falconeye:latest
    command: >
      uvicorn api.main:app
      --host 0.0.0.0
      --port 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    gpus: all

  gradio:
    image: ghcr.io/varun-sai-500/falconeye:latest
    command: python app.py
    ports:
      - "7860:7860"
    restart: unless-stopped
    gpus: all